version: '3.7'

services:
  movieloader:
    build:
      context: ./context/movie-loader
    image: movieloader
    container_name: movieloader
    depends_on:
      - kafka
    command: ["kafka:9092"]
    ports:
      - "8010:8010"
      - "18017:5005"
    environment:
      - JAVA_OPTS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - kafkastreams

  moviestreams:
    build:
      context: ./context/movie-streams
    image: moviestreams
    container_name: moviestreams
    depends_on:
      - kafka
    command: ["kafka:9092"]
    ports:
      - "8020:8020"
      - "18018:5005"
    environment:
      - JAVA_OPTS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - kafkastreams

  moviees:
    build:
      context: ./context/movie-es
    image: moviees
    container_name: moviees
    depends_on:
      - kafka
    command: ["kafka:9092"]
    ports:
      - "8030:8030"
      - "18019:5005"
    environment:
      - JAVA_OPTS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ELASTICSEARCH_HOSTS=http://es01:9200
    networks:
      - kafkastreams

  moviemongo:
    build:
      context: ./context/movie-mongo
    image: moviemongo
    container_name: moviemongo
    depends_on:
      - kafka
    command: ["kafka:9092"]
    ports:
      - "8040:8040"
      - "18020:5005"
    environment:
      - JAVA_OPTS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_MONGO_HOST=mongo
      - SPRING_MONGO_PORT=27017
    networks:
      - kafkastreams

  movieui:
    build:
      context: ./context/movie-ui
    image: movieui
    container_name: movieui
    ports:
      - "3000:3000"
    networks:
      - kafkastreams

networks:
  kafkastreams:
    driver: bridge