version: '3.7'

services:
  wordcountinput:
    build:
      context: ./context/word-count-input
    image: wordcountinput
    container_name: wordcountinput
    depends_on:
      - kafka
    command: ["kafka:9092"]
    ports:
      - "8012:8011"
      - "18017:5005"
    environment:
      - JAVA_OPTS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      #      - BOOTSTRAP_SERVERS_CONFIG=localhost:9092
      - KAFKA_SERVER=kafka:9092
    networks:
      - kafkastreams


  wordcount:
    build:
      context: ./context/word-count
    image: wordcount
    container_name: wordcount
    depends_on:
      - kafka
    command: ["kafka:9092"]
    ports:
      - "8010:8010"
      - "18015:5005"
    environment:
      - JAVA_OPTS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#      - BOOTSTRAP_SERVERS_CONFIG=localhost:9092
      - KAFKA_SERVER=kafka:9092
    networks:
      - kafkastreams

  wordcountoutput:
    build:
      context: ./context/word-count-output
    image: wordcountoutput
    container_name: wordcountoutput
    depends_on:
      - kafka
      - es01
    links:
      - es01
    command: ["kafka:9092"]
    ports:
      - "8011:8011"
      - "18016:5005"
    environment:
      - JAVA_OPTS= -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#      - BOOTSTRAP_SERVERS_CONFIG=localhost:9092
      - KAFKA_SERVER=kafka:9092
      - ELASTICSEARCH_HOSTS=http://es01:9200
    networks:
      - kafkastreams



networks:
  kafkastreams:
    driver: bridge