server:
  port: 8030
  servlet:
    context-path: /es7

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    group-id: moviees
    auto-offset-reset: earliest
    max-poll-records: 10000
  es:
    host: ${ELASTICSEARCH_HOSTS:http://localhost:9200}