server:
  port: 8020
  servlet:
    context-path: /loader

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    group-id: word-count
    auto-offset-reset: earliest
    max-poll-records: 10000
  es:
    host: ${ELASTICSEARCH_HOSTS:http://localhost:9200}